define({
	"language": "es",
	"app-title": "Buscador de propiedad",
	"app-subtitle": "Puede utilizar esta aplicación para buscar y comparar los datos de las propiedades en la Ciudad de Filadelfia",
	"address": "Dirección",
	"account": "Cuenta",
	"account-no": "N.° de cuenta",
	"block": "Bloque",
	"intersection": "intersección",
	"unit": "Unidad",
	"unit-colon": "Unidad:",
	"hundred": "Cien",
	"street": "Calle",
	"street1": "Calle 1",
	"street2": "Calle 2",
	"search": "Búsqueda",
	"i-accept": "Acepto",
	"new-search": "Búsqueda nueva",
	"try-again": "Intente de nuevo",
	"more": "Más",
	"view-tax-balances": "Ver saldos de impuestos",
	"submit-inquiry": "Enviar consulta",
	"check-eligibility": "Verificar elegibilidad",
	"ex": "ej.",
	"loading": "Cargando",
	"num-results-found": "{0} resultados encontrados",
	"sale-details": "Detalles de venta",
	"select": "Seleccionar...",
	"multiple-results": "Varias propiedades encontradas",
	"error": "Error",
	"assessment": "Avalúo",
	"tax-loop": "Programa de impuestos LOOP",
	"account-info": "Información de la cuenta",
	"owners": "Propietario(s)",
	"mailing-address": "Dirección postal",
	"property-unit": "Unidad de la propiedad",
	"property-zip": "Código postal de la propiedad",
	"sale-date": "Fecha de venta",
	"sale-price": "Precio de venta",
	"homestead": "Casa",
	"yes": "Sí",
	"no": "No",
	"property-chars": "Características de la propiedad",
	"land-area": "Área del terreno",
	"num-sqft": "{0} pies cuadrados",
	"improvement-area": "Área de mejora",
	"improvement-desc": "Descripción de la mejora",
	"beginning-point": "Punto de partida",
	"ext-condition": "Condición del exterior",
	"zoning": "Zonificación",
	"proposed-valuation": "Tasación propuesta",
	"proposed-not-available": "Los valores propuestos aún no están disponibles",
	"certified-history": "Historial de tasación certificada",
	"year": "Año",
	"market-value": "Valor comercial",
	"assessed-land-taxable": "Avalúo de la propiedad (Imponible)",
	"assessed-imp-taxable": "Avalúo de la mejora (Imponible)",
	"assessed-land-exempt": "Avalúo de la propiedad (Exento)",
	"assessed-imp-exempt": "Avalúo de la mejora (Exento)",
	"total-assessment": "Avalúo total",
	"loop-full-name": "Programa para propietarios ocupantes de muchos años (LOOP, por sus siglas en inglés)",
	"loop-property-not-eligible": "Esta propiedad no cumple los requisitos para participar en el Programa para propietarios ocupantes de muchos años. Para obtener información acerca de otros programas de reducción de impuestos, visite {0}www.phila.gov/revenue{1}.",
	"loop-not-eligible": "Al parecer, usted no cumple los requisitos para participar en el Programa LOOP pero es posible que cumpla los requisitos para participar en otros programas. Para obtener información acerca de programas de reducción de impuestos, visite {0}www.phila.gov/revenue{1}.",
	"loop-eligible": "Es posible que cumpla los requisitos para participar en el Programa LOOP pero debe presentar su solicitud antes del 17 de febrero de 2015. Utilice la solicitud que se le envió por correo postal. Para obtener más información, visite {0}www.phila.gov/loop{1} o llame al 215-686-9200.",
	"loop-instructions": "Algunos de los propietarios de casas por muchos años, cuyas propiedades han aumentado de valor de forma radical y que cumplen con otros requisitos, son elegibles para recibir asistencia de la Ciudad de Filadelfia para hacer frente a los aumentos importantes en su factura de impuestos a la propiedad.  Utilice este formulario para comprobar si cumple los requisitos.",
	"loop-q1": "1. ¿Al menos una de las siguientes opciones es verdadera? Paga sus impuestos de bienes inmuebles en su totalidad, está al día con un plan de pago o ha presentado una solicitud de plan de pago ante el Departamento de Hacienda.",
	"loop-q2": "2. ¿Ha sido dueño y ocupante continuo de la propiedad como su residencia principal y domicilio al menos desde el 1 de julio de 2003?",
	"loop-q3": "3. ¿Cuántas personas viven en esta casa?",
	"loop-q4": "4. ¿Cuál es el ingreso anual total de todos los integrantes del hogar?",
	"bill-without-loop": "Factura de impuestos de 2015 sin el Programa LOOP:",
	"bill-with-loop": "Factura de impuestos de 2015 con el Programa LOOP:",
	"loop-savings": "Ahorro potencial:",
	"loop-pending-legislation": "El Programa LOOP está a la espera de aprobación de la legislación por parte del Estado de Pensilvania y puede estar sujeto a límites de ingresos con base en el tamaño del hogar, de la siguiente manera:",
	"num-person": "{0} personas",
	"ext_cond_0": "No corresponde",
	"ext_cond_1": "Otro",
	"ext_cond_2": "Nuevo/rehabilitado",
	"ext_cond_3": "Superior al promedio",
	"ext_cond_4": "Promedio",
	"ext_cond_5": "Por debajo del promedio",
	"ext_cond_6": "Vacante",
	"ext_cond_7": "Sellado/Conforme a nivel estructural",
	"disc-terms": "Al utilizar esta solicitud, usted está de acuerdo con sus {0}Términos de uso{1}.",
	"tou-title": "Términos de uso",
	"tou1": "La oficina de avalúo catastral (OPA, por sus siglas en inglés) de la Ciudad de Filadelfia hace todo lo que está a su alcance para crear y publicar en este sitio web la información fidedigna y actual que tiene disponible. Los registros de propiedad de OPA los conforman las escrituras registradas en el Departamento de Hacienda (DOR, por sus siglas en inglés) de la Ciudad de Filadelfia y OPA revisa estos registros para comprobar su exactitud tan a menudo como le es posible. Sin embargo, usted es responsable de verificar la exactitud de la información en este sitio web revisando la(s) escritura(s) correspondiente(s).",
	"tou2": "OPA no es una empresa abstracta y no establece quién tiene el mejor título de propiedad si existiera un conflicto en los registros públicos de propiedad. La información en este sitio web no pretende indicar la calidad del título o la prioridad de participación en ninguna propiedad y se le recomienda no confiar en ella para tal fin.",
	"tou3": "Los valores comerciales y los valores catastrales publicados en este sitio podrían no reflejar los cambios realizados desde la última actualización en la base de datos de OPA . OPA no tiene información sobre el pago de impuestos de ninguna propiedad específica.",
	"tou4": "Todos los términos y condiciones adicionales de la Ciudad de Filadelfia, que se encuentran a continuación, se aplican a la información de este sitio de OPA y a su acceso y uso de esta información y del sitio.",
	"disclaimer-title": "Descargo de responsabilidad",
	"disclaimer": "La ciudad de Filadelfia y OPA (denominadas en conjunto, la Ciudad) no ofrecen garantía ni representación alguna, expresa o implícita, con respecto a la calidad, contenido, exactitud, integridad, actualidad, ausencia de virus informáticos, adecuación para cualquier propósito en particular o no infracción de los derechos de propiedad de cualquier información publicada en este sitio o de cualquier diseño, texto, gráficos, imágenes, páginas, interfaces, vínculos, software u otros materiales, documentos y artículos que contenga, se muestren o publiquen en este sitio. Todos estos artículos y materiales se proporcionan \"tal cual\" y usted es el único y absoluto responsable del uso de los mismos y de cualquier resultado o consecuencia provocada por su uso. En muchos casos han sido recopilados a partir de varias fuentes, entre ellas fuentes fuera del control de la Ciudad de Filadelfia, y están sujetos a cambios sin previo aviso por parte de la Ciudad. Excepto como se indica a continuación, el uso comercial (que incluye, pero no se limita a, la venta a otros) está prohibido sin el permiso previo por escrito de la Ciudad. La medida en la que utilice, aplique o ponga en práctica esta información en su propio sistema de información o en otro lugar, o para sus propios fines, lo hace bajo su propio riesgo. De ninguna manera serán responsables la Ciudad, OPA u otras agencias de la Ciudad, o los funcionarios, empleados, agentes o representantes de cualquiera de las anteriores de ningún daño directo, indirecto, especial, punitivo, incidental, ejemplar o resultante que surja de su acceso o uso del sitio o de cualquier información que se muestre en el sitio, o que surjan del sitio o de cualquier elemento contenido o mostrado en el sitio. Nada que esté incluido o que se muestre en este sitio constituye, ni pretende constituir, un asesoramiento legal por parte de la Ciudad o cualquiera de sus agencias, funcionarios, empleados, agentes, abogados, o representantes.",
	"external-sites-title": "Sitios externos",
	"external-sites": "Este sitio puede contener enlaces a otros sitios en Internet administrados por terceros ajenos a la Ciudad y pueden contener información que puede ser de interés para nuestros usuarios. La Ciudad no tiene control sobre estos sitios y no es responsable de su contenido ni de la disponibilidad de los sitios o su contenido. Nuestros enlaces a estos sitios no son un aval o recomendación de estos sitios o de productos o servicios comerciales cualesquiera que puedan ser anunciados o estar disponibles en ellos, ni tampoco significa que la Ciudad apoye necesariamente las opiniones o hechos que se presenten en ellos. Las preguntas e inquietudes que tenga sobre el contenido de cualquier sitio externo vinculado deberán dirigirse directamente al administrador del sitio externo.",
	"copyright-title": "Derechos de autor, marcas comerciales y de servicio",
	"copyright": "Las marcas comerciales y de servicio que se encuentren o se muestren en el sitio y el contenido de los sitios vinculados administrados por terceros son propiedad de sus respectivos dueños. Todos los demás diseños, información, textos, gráficos, imágenes, páginas, interfaces, enlaces, software, y otros artículos y materiales contenidos o mostrados en este sitio y la selección y arreglos de los mismos, son propiedad de la Ciudad de Filadelfia. Todos los derechos reservados. Se autoriza la copia electrónica e impresión de la información del sitio solo para uso personal o para compartirla con otras personas con la condición de que toda la información copiada, impresa o compartida no tenga costo para los beneficiarios y se imprima exactamente como está en el sitio, sin agregar o modificar nada.",
	"communications-title": "Comunicaciones a través del sitio",
	"communications": "La comunicación enviada a través de correo electrónico, mensajería o cualquier otra función de comunicación de cualquier sitio web de la Ciudad no constituirá, en ningún caso, un aviso legal o de otro tipo para la Ciudad, OPA, cualquiera de las otras agencias de la Ciudad o para cualquiera de los funcionarios, empleados , agentes o representantes de OPA o de la Ciudad, se incluye pero no se limita a (i) un aviso legal requerido por las leyes federales, estatales o locales, normas o regulaciones con respecto a cualquier reclamación o fundamento de demanda existente o potencial en contra la Ciudad o de cualquiera de sus agencias, funcionarios, empleados, agentes o representantes, (ii) cualquier forma de notificación requerida de conformidad con las regulaciones o políticas de OPA o de las leyes federales, estatales o locales aplicables a OPA, o (iii) cualquier forma de notificación requerida en virtud de cualquier documento expedido por OPA.",
	"misc-disc-title": "Varios",
	"misc-disc": "Los términos y condiciones anteriores y todas las disputas que surjan en virtud de ellos se regirán, interpretarán y resolverán de conformidad con las leyes del Estado de Pensilvania. La Ciudad se reserva el derecho de revisar y modificar de otro modo los términos y condiciones anteriores en cualquier momento y sin previo aviso. Los encabezados son solamente para conveniencia y no definen, limitan, amplían o describen de ninguna manera la intención de cualquier disposición de estos Términos de uso y Aviso legal.",
	"disc-revenue-taxes": "Nota: El Departamento de Hacienda es responsable de la recaudación de impuestos de bienes inmuebles.  Visite el {0}sitio web del Departamento de Hacienda{1} para obtener información sobre la facturación, recaudación y contabilización de los impuestos de bienes inmuebles o llame al 215-686-6442.",
	"disc-homestead": "Si es aprobado por la Exención Homestead, la cantidad se puede encontrar en la columna 'Exento'. Usted no es elegible para la Exención Homestead si ya tienes una reducción o está inscrito en el Programa El veterano Ocupantes Propietario (LOOP) .",
	"no-matches": "No se han encontrado resultados para {0}.",
	"for-best-results": "Para obtener los mejores resultados, intente escribir el número de cuenta de su propiedad.",
	"click-submit-inquiry": "Haga clic aquí para enviar una consulta",
	"error-account-fail": "Se produjo un error mientras se buscaba la propiedad en la base de datos. Intente de nuevo.",
	"error-loop-fail": "Se produjo un error mientras se buscaba la propiedad en la base de datos de LOOP. Intente de nuevo.",
	"error-address-fail": "Se produjo un error mientras se verificaba la dirección. Intente de nuevo.",
	"error-default": "Se produjo un error. Intente de nuevo.",
	"field-required": "Este campo es obligatorio."
});