define({
    "language": "rev",
    "app-title": "hcraeS ytreporP",
    "app-subtitle": "aihpledalihP fo ytiC eht ni atad ytreporp erapmoc dna hcraes ot noitacilppa siht esu nac uoY",
    "address": "sserddA",
    "account": "tnuoccA",
    "account-no": "# tnuoccA",
    "block": "kcolB",
    "intersection": "noitcesretnI",
    "unit": "tinU",
    "unit-colon": ":tinU",
    "hundred": "derdnuH",
    "street": "teertS",
    "street1": "1 teertS",
    "street2": "2 teertS",
    "search": "hcraeS",
    "i-accept": "tpeccA I",
    "new-search": "hcraeS weN",
    "try-again": "niagA yrT",
    "more": "eroM",
    "view-tax-balances": "secnalaB xaT weiV",
    "submit-inquiry": "yriuqnI na timbuS",
    "check-eligibility": "ytilibigilE kcehC",
    "ex": ".xe",
    "loading": "gnidaoL",
    "num-results-found": "dnuof stluser {0}",
    "sale-details": "sliateD elaS",
    "select": "...tceleS",
    "multiple-results": "dnuoF seitreporP elpitluM",
    "error": "rorrE",
    "assessment": "tnemssessA",
    "tax-loop": "POOL xaT",
    "account-info": "noitamrofnI tnuoccA",
    "owners": ")s(renwO",
    "mailing-address": "sserddA gniliaM",
    "property-unit": "tinU ytreporP",
    "property-zip": "piZ ytreporP",
    "sale-date": "etaD elaS",
    "sale-price": "ecirP elaS",
    "homestead": "daetsemoH",
    "yes": "seY",
    "no": "oN",
    "property-chars": "scitsiretcarahC ytreporP",
    "land-area": "aerA dnaL",
    "num-sqft": "tFqS {0}",
    "improvement-area": "aerA tnemevorpmI",
    "improvement-desc": "noitpircseD tnemevorpmI",
    "beginning-point": "tnioP gninnigeB",
    "ext-condition": "noitidnoC roiretxE",
    "zoning": "gninoZ",
    "proposed-valuation": "noitaulaV desoporP",
    "proposed-not-available": "tey elbaliava ton seulav desoporP",
    "certified-history": "yrotsiH noitaulaV deifitreC",
    "year": "raeY",
    "market-value": "eulaV tekraM",
    "assessed-land-taxable": ")elbaxaT( dnaL dessessA",
    "assessed-imp-taxable": ")elbaxaT( tnemevorpmI dessessA",
    "assessed-land-exempt": ")tpmexE( dnaL dessessA",
    "assessed-imp-exempt": ")tpmexE( tnemevorpmI dessessA",
    "total-assessment": "tnemssessA latoT",
    "loop-full-name": ")POOL( margorP stnapuccO renwO mretgnoL",
    "loop-property-not-eligible": ".{0}www.phila.gov/revenue{1} tisiv ,smargorp feiler xat rehto tuoba noitamrofni roF .margorP stnapuccO renwO emitgnoL eht rof elbigile ton si ytreporp sihT",
    "loop-not-eligible": ".{0}www.phila.gov/revenue{1} tisiv ,smargorp feiler xat tuoba noitamrofni roF .smargorp rehto rof elbigile eb yam uoy tub ,POOL rof elbigile raeppa ton od uoY",
    "loop-eligible": ".0029-686-512 llac ro {0}www.phila.gov/loop{1} tisiv noitamrofni erom roF .uoy ot deliam noitacilppa eht esU .5102 ,71 February yb ylppa tsum uoy tub ,POOL rof elbigile eb yam uoY",
    "loop-instructions": ".elbigile era uoy fi kcehc ot mrof siht esU  .sllib xat ytreporp rieht ni sesaercni tnacifingis tsniaga aihpledalihP fo ytiC eht morf feiler rof elbigile era ,stnemeriuqer rehto teem ohw dna ,yllacitamard desaercni evah seulav ytreporp esohw srenwoemoh emitgnol niatreC",
    "loop-q1": "?euneveR fo tnemtrapeD eht yb noitanimreted gnidnep si taht noitacilppa tnemeerga tnemyap a ot tcejbus )c( ro ,tluafed ni ton si taht tnemeerga tnemyap a ot tcejbus )b( ,tnerruc )a( :ytreporp eht no sexaT etatsE laeR lla erA .1",
    "loop-q2": "?3002 ,1 yluJ tsael ta ecnis elicimod dna ecnediser yramirp ruoy sa ytreporp eht deipucco dna denwo ylsuounitnoc uoy evaH .2",
    "loop-q3": "?dlohesuoh siht ni evil elpoep ynam woH .3",
    "loop-q4": "?dlohesuoh eht fo srebmem lla rof emocni launna latot eht si tahW .4",
    "bill-without-loop": ":POOL tuohtiw lliB xaT 5102",
    "bill-with-loop": ":POOL htiw lliB xaT 5102",
    "loop-savings": ":sgnivas laitnetoP",
    "loop-pending-legislation": ":swollof sa ,ezis dlohesuoh nopu desab stimil emocni ot tcejbus eb yam POOL  ,ainavlysnneP fo htlaewnommoC eht yb noitalsigel fo egassap eht gnidneP",
    "num-person": "nosreP {0}",
    "disc-terms": ".{0}esU fo smreT{1} sti ot eerga uoy noitacilppa siht gnisu yB",
    "tou-title": "esU fo smreT",
    "tou1": ".)s(deed gnidnopserroc eht ot gnirrefer yb etis siht no noitamrofni eht fo ycarucca eht gniyfirev rof ,revewoh ,elbisnopser era uoY .elba era ew sa netfo sa ycnerruc rof sdrocer eseht esiver ew dna ,)ROD( sdroceR fo tnemtrapeD aihpledalihP fo ytiC eht htiw dedrocer sa sdeed no desab era sdrocer pihsrenwo ruO .ti ot elbaliava noitamrmofni tnerruc dna etarucca tsom eht etis siht no hsilbup dna ecudorp ot troffe yreve sekam )APO( aihpledalihP fo ytiC eht fo tnemssessA ytreporP fo eciffO ehT",
    "tou2": ".esoprup taht rof ti no yler ot ton desivda era uoy dna ,ytreporp yna ni tseretni fo ytiroirp ro eltit fo ytilauq eht etacidni ot dednetni ton si etis siht no noitamrofni ehT .pihsrenwo ot sa tcilfnoc sdrocer cilbup eht fi ytreporp a ot eltit retteb eht sah ohw enimreted ton od ew dna ynapmoc tcartsba na ton si APO ehT",
    "tou3": ".ytreporp ralucitrap yna rof diap neeb evah sexat rehtehw ot sa noitamrofni yna evah ton od eW .esabatad ruo ni etadpu tsal eht ecnis edam segnahc tcelfer ton yam etis siht no dehsilbup seulav dessessa dna seulav tekram ehT",
    "tou4": ".etis eht dna noitamrofni siht fo esu dna ot ssecca ruoy ot dna etis APO siht no noitamrofni eht ot ylppa lla woleb snoitidnoc dna smret aihpledalihP fo ytiC lanoitidda ehT",
    "disclaimer-title": "remialcsiD",
    "disclaimer": ".sevitatneserper ro ,syenrotta ,stnega ,seeyolpme ,sreciffo ,seicnega sti fo yna ro ytiC eht yb ecivda lagel etutitsnoc ot dednetni si ro setutitsnoc etis siht no deyalpsid ro ni deniatnoc gnihtoN .etis eht no deyalpsid ro ni deniatnoc gnihtyna morf ro etis eht morf gnisira esiwrehto ro ,etis eht no deyalpsid noitamrofni yna ro etis eht gnisu ro gnissecca ruoy gnisira segamad laitneuqesnoc ro yralpmexe ,latnedicni ,evitinup ,laiceps ,tceridni ,tcerid yna rof elbail eb gniogerof eht fo yna fo sevitatneserper ro ,stnega ,seeyolpme ,sreciffo eht ro ,seicnega rehto s'ytiC eht ,APO eht ,ytiC eht llahs tneve on nI .ksir nwo ruoy ta os od uoy ,sesoprup nwo ruoy rof esiwrehto ro ,gnittes rehto ro metsys noitamrofni nwo ruoy ni noitamrofni siht tnemelpmi ro ,ylppa ,esu uoy tnetxe eht oT .ytiC eht fo noissimrep nettirw roirp eht tuohtiw detibihorp si )srehto ot elas ot detimil ton tub gnidulcni( esu laicremmoc ,woleb detats sa tpecxE .ytiC eht morf eciton tuohtiw egnahc ot tcejbus era dna ,aihpledalihP fo ytiC eht fo lortnoc eht dnoyeb secruos gnidulcni ,secruos fo yteirav a morf delipmoc neeb evah yeht ,sesac ynam nI .esu ruoy fo secneuqesnoc ro stluser yna rof dna meht fo esu ruoy rof elbisnopser ylelos dna ylluf era uoy dna ,sisab 'si sa' na no dedivorp era slairetam dna smeti hcus llA .etis siht no dehsilbup ro deyalpsid ro ni deniatnoc smeti dna ,stnemucod ,slairetam rehto ro ,erawtfos ,sknil ,secafretni ,segap ,segami ,scihparg ,txet ,ngised eht fo yna ro ,etis siht no dehsilbup noitamrofni eht fo yna fo ,sthgir yrateirporp fo tnemegnirfni-non ro ,esoprup ralucitrap yna rof ytilibatius ,suriv retupmoc morf modeerf ,ycnerruc ,ssenetelpmoc ,ycarucca ,tnetnoc ,ytilauq eht ot tcepser htiw ,deilpmi ro sserpxe ,reveostahw noitatneserper ro ytnarraw on ekam )ytiC eht ,ylevitcelloc( APO eht dna aihpledalihP fo ytiC ehT",
    "external-sites-title": "setis lanretxE",
    "external-sites": ".etis lanretxe eht fo rotartsinimda eht ot yltcerid desserdda eb dluohs etis lanretxe deknil yna fo tnetnoc eht gnidrager snrecnoc dna snoitseuQ .meht no detneserp stcaf ro sweiv eht troppus ylirassecen ytiC eht seod ron ;meht no elbaliava ro desitrevda eb yam taht secivres ro stcudorp rehto ro laicremmoc yna fo ro setis eht fo noitadnemmocer ro tnemesrodne na ton era setis eseht ot sknil ruO .tnetnoc rieht ro setis eht fo ytilibaliava eht rof ro tnetnoc rieht rof elbisnopser ton si dna setis eseht revo lortnoc on sah ytiC ehT .sresu ruo ot tseretni fo eb yam taht noitamrofni evah dna ytiC eht naht rehto seitrap yb detarepo era taht tenretnI eht no setis rehto ot sknil niatnoc yam etis sihT",
    "copyright-title": "skramecivres dna skramedart ,thgirypoC",
    "copyright": ".noitacifidom ro noitidda yna tuohtiw ,etis eht no detnirp sa yltcaxe dna stneipicer eht ot tsoc tuohtiw si derahs ro/dna ,detnirp ,deipoc noitamrofni lla taht noitidnoc eht no snosrep rehto htiw derahs eb ot ro ,ylno esu lanosrep rof si etis eht morf noitamrofni tnirp ot dna yllacinortcele ypoc ot noissimreP .devreser era sthgir llA .aihpledalihP fo ytiC eht fo ytreporp eht era ,foereht stnemegnarra dna noitceles eht dna ,etis siht no deyalpsid ro ni deniatnoc slairetam dna smeti rehto dna ,erawtfos ,sknil ,secafretni ,segap ,segami ,scihparg ,txet ,noitamrofni ,ngised rehto llA .srenwo evitcepser rieht fo ytreporp eht era ,seitrap driht yb detarepo setis deknil fo stnetnoc eht dna ,etis eht no deyalpsid ro ni deniatnoc skramedart dna skramecivreS",
    "communications-title": "etis eht hguorht snoitacinummoC",
    "communications": ".APO eht yb deussi tnemucod yna ot tnausrup deriuqer eciton fo mrof yna )iii( ro ;APO eht ot gniylppa wal lacol ro ,etats ,laredef yna ro seicilop ro snoitaluger s'APO eht ot tnausrup deriuqer eciton fo mrof yna )ii( ;sevitatneserper ro ,stnega ,seeyolpme ,sreciffo ,seicnega sti fo yna ro ytiC eht tsniaga noitca fo esuac ro mialc laitnetop ro gnitsixe yna ot tcepser htiw snoitaluger ro ,selur ,swal lacol ro ,etats ,laredef yb deriuqer eciton lagel )i( ot detimil ton tub gnidulcni ,ytiC eht ro APO eht fo sevitatneserper ro ,stnega ,seeyolpme ,sreciffo eht fo yna ot ro ,seicnega rehto s'ytiC eht fo yna ,APO eht ,ytiC eht ot eciton rehto ro lagel etutitsnoc etis bew ytiC yna fo snoitcnuf snoitacinummoc rehto ro gnigassem ,liam-e eht hguorht edam noitacinummoc yna llahs tneve on nI",
    "misc-disc-title": "suoenallecsiM",
    "misc-disc": ".remialcsiD dna esU fo smreT eseht fo noisivorp yna fo tnetni eht ebircsed ro dnetxe ,timil ,enifed yaw on ni dna ylno ecneinevnoc rof era sgnidaeH .eciton tuohtiw dna emityna ta snoitidnoc dna smret gniogerof eht egnahc esiwrehto dna esiver ot thgir eht sevreser ytiC ehT .ainavlysnneP fo htlaewnommoC eht fo swal eht htiw ecnadrocca ni dediced dna deurtsnoc ,denrevog eb llahs meht rednu gnisira setupsid lla dna snoitidnoc dna smret gniogerof ehT",
    "disc-revenue-taxes": ".2446-686-512 llac ro sexat etatse laer fo gnitnuocca dna gnitcelloc ,gnillib eht gnidrager noitamrofni rof {0}etisbeW euneveR fo tnemtrapeD{1} eht tisiv esaelP  .sexat etatse laer gnitcelloc rof elbisnopser si euneveR fo tnemtrapeD ehT :etoN",
    "disc-homestead": ".)POOL( margorP stnapuccO renwO emitgnoL eht ni dellorne era ro tnemetaba na evah ydaerla uoy fi noitpmexE daetsemoH eht rof elbigile ton era uoY .nmuloc 'tpmexE' eht ni dnuof eb nac tnuoma eht ,noitpmexE daetsemoH eht rof devorppa fI",
    "no-matches": ".{0} rof dnuof sehctam oN",
    "for-best-results": ".ytreporp ruoy fo rebmun tnuocca eht gniretne yrt ,stluser tseb roF",
    "click-submit-inquiry": "yriuqni na timbus ot ereh kcilC",
    "error-account-fail": ".niaga yrt esaelP .esabatad eht ni ytreporp eht gnidnif elihw derrucco rorre nA",
    "error-loop-fail": ".niaga yrt esaelP .esabatad eht ni ytreporp eht gnidnif elihw derrucco rorre nA",
    "error-address-fail": ".niaga yrt esaelP .sserdda eht gniyfirev elihw derrucco rorre nA",
    "error-default": ".niaga yrt esaelP .derrucco rorre nA",
    "field-required": ".deriuqer si dleif sihT"
});