define({
	"language": "fr",
	"app-title": "Recherche de biens immobiliers",
	"app-subtitle": "Vous pouvez utiliser cette application pour rechercher et pour comparer des données immobilières dans la ville de Philadelphie",
	"address": "Adresse",
	"account": "Compte",
	"account-no": "Numéro de compte",
	"block": "Pâté",
	"intersection": "Intersection",
	"unit": "Unité",
	"unit-colon": "Unité",
	"hundred": "Cent",
	"street": "Rue",
	"street1": "Rue 1",
	"street2": "Rue 2",
	"search": "Chercher",
	"i-accept": "J'accepte",
	"new-search": "Nouvelle recherche",
	"try-again": "Essayez de nouveau",
	"more": "Plus",
	"view-tax-balances": "Voir les soldes d'impôts",
	"submit-inquiry": "Soumettre une demande",
	"check-eligibility": "Confirmer l'admissibilité",
	"ex": "ex.",
	"loading": "En cours de chargement",
	"num-results-found": "{0} résultats a été trouvés",
	"sale-details": "Détails de vente",
	"select": "Sélectionner…",
	"multiple-results": "Multiples propriétés ont été trouvées",
	"error": "Erreur",
	"assessment": "Évaluation",
	"tax-loop": "Taxe LOOP",
	"account-info": "Données du compte",
	"owners": "Propriétaire(s)",
	"mailing-address": "Adresse postale",
	"property-unit": "Numéro d'unité",
	"property-zip": "Code postal",
	"sale-date": "Date de vente",
	"sale-price": "Prix de vente",
	"homestead": "Propriété familiale",
	"yes": "Oui",
	"no": "Non",
	"property-chars": "Caractéristiques du bien",
	"land-area": "Superficie de terre",
	"num-sqft": "{0} pi.ca.",
	"improvement-area": "Zone d'amélioration",
	"improvement-desc": "Description d'amélioration",
	"beginning-point": "Point de départ",
	"ext-condition": "État extérieur",
	"zoning": "Zonage",
	"proposed-valuation": "Évaluation proposée",
	"proposed-not-available": "Valeurs proposées ne sont pas encore disponibles",
	"certified-history": "Historique d'évaluation certifiée",
	"year": "Année",
	"market-value": "Valeur marchande",
	"assessed-land-taxable": "Terre évaluée (taxable)",
	"assessed-imp-taxable": "Amélioration évaluée (taxable)",
	"assessed-land-exempt": "Terre évaluée (non taxable)",
	"assessed-imp-exempt": "Amélioration évaluée (non taxable)",
	"total-assessment": "Évaluation totale",
	"loop-full-name": "Programme pour les propriétaires occupants à long terme (LOOP)",
	"loop-property-not-eligible": "Ce bien n'est pas admissible au Programme pour les propriétaires occupants à long terme. Pour découvrir d'autres programmes d'allégement fiscal, veuillez visiter le site {0}www.phila.gov/revenue{1}.",
	"loop-not-eligible": "Vous ne semblez pas être admissible à LOOP, mais vous pouvez être admissible à d'autres programmes. Pour découvrir des programmes d'allégement fiscal, veuillez visiter le site {0}www.phila.gov/revenue{1}.",
	"loop-eligible": "Vous pouvez être admissible à LOOP, mais vous devez faire demande avant le 17 février 2015. Utilisez le formulaire de demande qui vous a été envoyé. Pour plus d'informations, veuillez visiter le site {0}www.phila.gov/loop{1} ou téléphoner au 215-686-9200.",
	"loop-instructions": "Certains propriétaires à long terme, dont les valeurs des biens immobiliers ont augmenté considérablement et qui répondent à d'autres critères, sont admissibles à obtenir un allégement de la ville de Philadelphie contre des accroissements des taxes immobilières. Utilisez ce formulaire pour déterminer si vous êtes admissible.",
	"loop-q1": "1. Est-ce que l'une des conditions suivantes vraie? Vos taxes immobilières sont payées en entier, vous êtes à jour d'un plan de paiement ou vous avez soumis une demande d'un plan de paiement au Ministère du Revenu.",
	"loop-q2": "Avez-vous possédé et habité de façon continue le bien immobilier comme votre résidence principale et votre domicile depuis au moins le 1 juillet 2003 ?",
	"loop-q3": "Combien des personnes habitent ce ménage ?",
	"loop-q4": "Quel est le revenu annuel total de tous les membres du ménage ?",
	"bill-without-loop": "Facture fiscale 2015 sans LOOP :",
	"bill-with-loop": "Facture fiscale 2015 avec LOOP :",
	"loop-savings": "Économies potentielles",
	"loop-pending-legislation": "En attente de l'adoption de la législation par le Commonwealth de la Pennsylvanie, LOOP peut être soumis aux limites de revenu, calculées en fonction de la taille du ménage comme suit :",
	"num-person": "{0} Personne",
	"ext_cond_0": "Non applicable",
	"ext_cond_1": "Autre",
	"ext_cond_2": "Nouveau/réhabilité",
	"ext_cond_3": "Supérieur à la moyenne",
	"ext_cond_4": "Moyenne",
	"ext_cond_5": "Inférieur à la moyenne",
	"ext_cond_6": "Inoccupé",
	"ext_cond_7": "Scellé/structurellement conforme",
	"disc-terms": "En utilisant ce formulaire de demande, vous acceptez ses {0}Conditions d'utilisation{1}.",
	"tou-title": "Conditions d'utilisation",
	"tou1": "Le Bureau de l'Évaluation des biens immobiliers (OPA) de la ville de Philadelphie s'efforce de produire et de publier sur ce site les informations les plus précises et récentes dont il dispose. Les registres de propriété de l'OPA sont fondés sur les titres de propriété enregistrés auprès du Ministère des Dossiers (DOR) de la ville  de Philadelphie, et l'OPA révise ces dossiers pour vérifier l'exactitude aussi souvent que possible. Mais vous êtes responsable de vérifier l'exactitude des informations sur ce cite en vous référant au titre/aux titres correspondant(s). ",
	"tou2": "L'OPA n'est pas une société abstraite, et dans les cas où les registres publiques de propriété sont contradictoires, nous ne déciderons pas qui a le titre plus fort de propriété. Les informations sur ce site ne visent à déterminer ni la qualité du titre ni la priorité de l'intérêt dans un bien, et vous ne devriez pas les utiliser à cette fin. ",
	"tou3": "Les valeurs marchandes et les valeurs évaluées publiées sur ce site ne reflètent pas forcément des changements effectués depuis la dernière mise à jour dans la base de données de l'OPA. L'OPA ne dispose d'aucune information lui permettant de vérifier si les taxes ont été payées sur un bien immobilier.",
	"tou4": "Toutes les modalités et conditions additionnelles de la ville de Philadelphie qui suivent s'appliquent aux informations sur ce site de l'OPA et à votre accès à et utilisation de ces informations et ce site.   ",
	"disclaimer-title": "Clause de non-responsabilité",
	"disclaimer": "La ville de Philadelphie et l'OPA (collectivement, la Ville) ne font aucune démarche et ne font aucune garantie de quelque sorte, expresses ou implicite, concernant la qualité, le contenu, l'exactitude, l'exhaustivité, l'actualité, l'absence de virus informatique, l'aptitude à servir à un usage particulier ou le respect des droits de propriété de toute information publiée sur ce site, ou de tout dessin, texte, graphique, image, page, interface, lien, logiciel ou autres matériels, documents et articles contenus dans ou présentés ou publiés sur ce site. Tous ces articles et matériels sont fournis « tels quels », et vous êtes entièrement et exclusivement responsable de votre utilisation de ceux-ci et de tout résultat ou conséquence de votre utilisation. Dans bien des cas, ils ont été compilés à partir de diverses sources, y compris des sources qui échappent au contrôle de la ville de Philadelphie, et ils sont sujets à changement sans préavis de la Ville. Sauf disposition contraire ci-après, l'utilisation à des fins commerciales, incluant sans s'y limiter la vente, est interdit sans l'accord préalable et écrit de la Ville. Dans la mesure où vous utilisez, appliquez ou mettez en œuvre ces informations dans votre propre système d'information ou dans un autre cadre, vous le faites à vos risques. En aucun case la Ville, l'OPA, les autres agences de la Ville ou les dirigeants, employés, agents ou représentants de ce qui précède ne seront tenus pour responsables de tout dommage direct, indirect, spécial, punitif, incident, exemplaire ou consécutif qui pourrait venir de votre accès à ou de votre utilisation du site ou de tout information présentée sur le site, ou qui pourrait venir autrement du site ou de toute chose contenue dans ou présentée sur le site. Rien de ce qui est contenu ou présenté sur ce site ne saurait être considéré comme constituant ou visant à constituer des conseils juridique de la Ville ou de ses agences, dirigeants, employés, agents, avocats ou représentants.",
	"external-sites-title": "Sites externes",
	"external-sites": "Ce site peut contenir des liens à d'autres sites Web qui ne sont pas administrées par la Ville et qui ont des informations de l'intérêt potentiel pour nos utilisateurs. La Ville n'exerce aucun contrôle sur ces sites et n'est pas responsable de leur contenu ou de la disponibilité de ces sites ou de leur contenu. Nos liens à ces sites ne constituent pas une approbation ou une recommandation de ces sites ou des produits ou services qui pourraient être affichés ou disponibles sur ces sites, et la Ville n'appuie pas forcément les avis ou les faits qui sont présentés sur ces sites. Les questions et les préoccupations concernant le contenu de tout site externe devraient être adressées directement à l'administrateur du site.",
	"copyright-title": "Droits d'auteur, marques commerciales et marques de service",
	"copyright": "Les marques de service et les marques commerciales contenues dans ou présentées sur le site, et le contenu des sites externes exploités par des tiers, sont la propriété de leurs détenteurs respectifs. Tout autre dessin, information, texte, graphique, image, page, interface, lien, logiciel et autres articles et matériels contenus dans ou présentés sur ce site, ainsi que leur sélection et leur disposition, sont la propriété de la ville de Philadelphie. Tous les droits sont réservés. Il est permis de faire des copies électroniques et d'imprimer des informations de ce cite pour usage personnel ou pour partages ces informations avec d'autres, à condition que toutes les informations copiées, imprimées et/ou partagées soient fournies gratuitement et exactement comme elles apparaissent sur le site, sans ajout ni modification. ",
	"communications-title": "Communications par le site",
	"communications": "En aucun cas les communications faites par e-mail, messagerie ou autres fonctions de communication des sites de la Ville ne constitue un avis juridique ou autre adressé à la Ville, l'OPA ou les autres agences de la Ville, ou à tout dirigeants, employés, agents ou représentants de l'OPA ou de la Ville, incluant sans s'y limiter à (i) l'avis juridique requis par les lois, règles ou règlements fédérales, d'État ou locales concernant toute demande ou cause d'action actuelle ou potentielle contre la Ville ou contre ses agences, dirigeants, employés, agents ou représentants; (ii) tout avis requis en vertu des règlements ou des politiques de l'OPA ou de toute loi fédérale, d'État ou locale qui s'applique à l'OPA; ou (iii) tout avis requis en vertu de tout document émis par l'OPA.",
	"misc-disc-title": "Divers",
	"misc-disc": "Les modalités et conditions ci-dessus et tout conflit qui apparaît sous celles-ci sont régis, interprétés et décidés conformément aux lois du Commonwealth de Pennsylvanie. La Ville se réserve le droit de réviser et de modifier les modalités et conditions ci-dessus à tout moment et sans préavis. Les titres sont ajoutés pour des raisons de commodité uniquement, et ils ne définissent, ne limitent, n'élargissent ou ne décrivent nullement le sens de l'une quelconque des dispositions de ces Conditions d'utilisation et de cette Clause de non-responsabilité.",
	"disc-revenue-taxes": "Note : Le Ministère du Revenu est chargé de récolter les taxes sur les biens immobiliers. Pour plus d'informations sur la facturation, le recouvrement et la comptabilité des taxes immobilières, veuillez visitez {0}Site du Ministère du Revenu{1} ou téléphoner au 215-686-6442.",
	"disc-homestead": "Si elle est approuvée à l'exemption de Homestead, le montant peut être trouvé dans la colonne 'exonéré'. Vous n'êtes pas admissible à l'exemption de Homestead si vous avez déjà un abattement ou êtes inscrit dans le Programme de longue date occupants propriétaire (LOOP).",
	"no-matches": "Aucune correspondance n'a été trouvée pour {0}",
	"for-best-results": "Pour les meilleurs résultats, saisissez le numéro de compte de votre bien immobilier.",
	"click-submit-inquiry": "Cliquez ici pour soumettre une demande",
	"error-account-fail": "Une erreur est survenue pendant la recherche du bien dans la base de données. Veuillez essayer de nouveau.",
	"error-loop-fail": "Une erreur est survenue pendant la recherche du bien dans la base de données. Veuillez essayer de nouveau.",
	"error-address-fail": "Une erreur est survenue pendant la vérification de l'adresse. Veuillez essayer de nouveau.",
	"error-default": "Une erreur est survenue. Veuillez essayer de nouveau.",
	"field-required": "Ce champ est obligatoire."
});