define({
	"language": "vi",
	"app-title": "Tìm kiếm tài sản",
	"app-subtitle": "Quý vị có thể sử dụng đơn xin này để tìm kiếm và so sánh các dữ liệu tài sản tại Thành phố Philadelphia",
	"address": "Địa chỉ",
	"account": "Tài khoản",
	"account-no": "Tài khoản #",
	"block": "Khối",
	"intersection": "Giao lộ",
	"unit": "Đơn vị",
	"unit-colon": "Đơn vị:",
	"hundred": "Trăm",
	"street": "Đường",
	"street1": "Đường 1",
	"street2": "Đường 2",
	"search": "Tìm kiếm",
	"i-accept": "Tôi đồng ý",
	"new-search": "Tìm kiếm mới",
	"try-again": "Thử lại",
	"more": "Thêm nữa",
	"view-tax-balances": "Xem số dư thuế",
	"submit-inquiry": "Gửi yêu cầu",
	"check-eligibility": "Kiểm tra điều kiện hội đủ",
	"ex": "ví dụ",
	"loading": "Đang tải",
	"num-results-found": "Tìm thấy {0} kết quả",
	"sale-details": "Chi tiết bán",
	"select": "Chọn...",
	"multiple-results": "Tìm thấy nhiều tài sản",
	"error": "Lỗi",
	"assessment": "Đánh giá",
	"tax-loop": "LOOP thuế",
	"account-info": "Thông tin tài khoản",
	"owners": "(Các) chủ sở hữu",
	"mailing-address": "Địa chỉ gửi thư",
	"property-unit": "Đơn vị tài sản",
	"property-zip": "Zip tài sản",
	"sale-date": "Ngày bán",
	"sale-price": "Giá bán",
	"homestead": "Nhà cửa vườn tược",
	"yes": "Có",
	"no": "Không",
	"property-chars": "Đặc điểm tài sản",
	"land-area": "Diện tích đất",
	"num-sqft": "{0} phút vuông",
	"improvement-area": "Diện tích cải thiện",
	"improvement-desc": "Miêu tả cải thiện",
	"beginning-point": "Điểm bắt đầu",
	"ext-condition": "Điều kiện ngoại thất",
	"zoning": "Quy hoạch",
	"proposed-valuation": "Định giá đề xuất",
	"proposed-not-available": "Chưa có giá trị đề xuất",
	"certified-history": "Lịch sử định giá có chứng nhận",
	"year": "Năm",
	"market-value": "Giá trị thị trường",
	"assessed-land-taxable": "Đất được định giá (Chịu thuế)",
	"assessed-imp-taxable": "Cải thiện được định giá (Chịu thuế)",
	"assessed-land-exempt": "Đất được định giá (Miễn thuế)",
	"assessed-imp-exempt": "Cải thiện được định giá (Miễn thuế)",
	"total-assessment": "Tổng đánh giá",
	"loop-full-name": "Chương Trình Chủ Sở Hữu Lâu Năm (LOOP)",
	"loop-property-not-eligible": "Tài sản này không đủ điều kiện tham gia Chương Trình Chủ Sở Hữu Lâu Năm. Để biết thông tin về các chương trình giảm thuế khác, hãy truy cập {0}www.phila.gov/revenue{1}.",
	"loop-not-eligible": "Có vẻ như quý vị không đủ điều kiện tham gia chương trình LOOP, nhưng quý vị có thể đủ điều kiện tham gia các chương trình khác. Để biết thông tin về các chương trình giảm thuế, hãy truy cập {0}www.phila.gov/revenue{1}.",
	"loop-eligible": "Quý vị có thể đủ điều kiện tham gia chương trình LOOP, nhưng quý vị phải nộp đơn trước ngày 17 tháng 2 năm 2015. Sử dụng đơn xin đã được gửi đến quý vị qua đường bưu điện. Để biết thêm thông tin, hãy truy cập {0}www.phila.gov/loop{1} hoặc gọi đến số 215-686-9200.",
	"loop-instructions": "Những chủ sở hữu lâu năm nhất định có giá trị tài sản tăng đáng kể, và những người đáp ứng các yêu cầu khác, đều đủ điều kiện được giảm từ Thành phố Philadelphia đối với trường hợp tăng hoá đơn thuế tài sản đáng kể của họ.  Sử dụng mẫu đơn này để kiểm tra xem quý vị có đủ điều kiện không.",
	"loop-q1": "1. Ít nhất một trong những điều sau đây là đúng sự thật phải không? Thuế bất động sản của quý vị đã được thanh toán đầy đủ, quý vị thực hiện đầy đủ trong chương trình thanh toán, hoặc quý vị đã nộp đơn xin tham gia chương trìnhthanh toán với Sở Thuế Vụ.",
	"loop-q2": "2. Quý vị có liên tục sở hữu và sử dụng tài sản là nơi cư ngụ chính và là nhà ở của quý vị ít nhất kể từ ngày 1 tháng 7 năm 2003 không?",
	"loop-q3": "3. Có bao nhiêu người sống trong hộ gia đình này?",
	"loop-q4": "4. Tổng thu nhập hàng năm cho tất cả các thành viên trong hộ gia đình là gì?",
	"bill-without-loop": "Hoá đơn thuế 2015 không có LOOP:",
	"bill-with-loop": "Hoá đơn thuế 2015 có LOOP:",
	"loop-savings": "Khoản tiết kiệm tiềm năng:",
	"loop-pending-legislation": "Trong khi chờ đợi ý kiến thông qua đạo luật của Khối Thịnh Vượng Pennsylvania,  LOOP có thể có các giới hạn thu nhập theo quy mô hộ gia đình như sau:",
	"num-person": "{0} Người",
	"ext_cond_0": "Không áp dụng",
	"ext_cond_1": "Khác",
	"ext_cond_2": "Mới / Sửa chữa lại",
	"ext_cond_3": "Trên trung bình",
	"ext_cond_4": "Trung bình",
	"ext_cond_5": "Dưới trung bình",
	"ext_cond_6": "Còn trống",
	"ext_cond_7": "Đã niêm phong / Tuân theo kết cấu",
	"disc-terms": "Khi sử dụng đơn xin này, quý vị đồng ý với {0}Điều khoản sử dụng{1}.",
	"tou-title": "Điều khoản sử dụng",
	"tou1": "Văn Phòng Thẩm Định Tài Sản (OPA) của Thành phố Philadelphia cố gắng thiết lập và công bố  thông tin chính xác và cập nhật nhất trên trang mạng này. Hồ sơ về quyền sở hữu của OPA dựa trên các chứng thư như được ghi chép với Bộ Văn Khố (DOR) của Thành phố Philadelphia, và OPA xét duyệt lại tính chính xác của những hồ sơ ghi chép này càng thường xuyên càng tốt. Tuy nhiên, quý vị có trách nhiệm xác minh tính chính xác của thông tin trên trang này bằng cách đối chiếu với (các) chứng thư tương ứng.",
	"tou2": "OPA không phải là một công ty hư ảo và chúng tôi không quyết định người nào có quyền tốt hơn đối với tài sản nếu hồ sơ công cộng cho thấy điều ngược lại đối với quyền sở hữu. Thông tin trên trang mạng này không nhằm cho biết đặc điểm của quyền sở hữu hoặc tính ưu tiên về quyền lợi trong bất kỳ tài sản nào, và quý vị không nên căn cứ vào thông tin đó vì mục đích đó.",
	"tou3": "Giá trị thị trường và giá trị thẩm định được công bố trên trang này có thể không phản ánh những thay đổi kể từ lần cập nhật cuối cùng trong cơ sở dữ liệu của OPA. OPA không có bất kỳ thông tin nào về việc có phải thanh toán thuế đối với bất kỳ tài sản cụ thể nào hay không.",
	"tou4": "Các điều khoản và điều kiện khác của Thành phố Philadelphia dưới đây áp dụng đối với các thông tin trên trang OPA này và đối với việc quý vị tiếp cận và sử dụng thông tin và trang mạng này.",
	"disclaimer-title": "Khước từ",
	"disclaimer": "Thành phố Philadelphia và OPA (gọi chung là Thành Phố) không đảm bảo hay tuyên bố, dù rõ ràng hay ngụ ý, về chất lượng, nội dung, tính chính xác, hoàn chỉnh, sự phổ biến, không có virút máy tính, tính thích hợp cho bất kỳ mục đích cụ thể nào, hoặc không vi phạm quyền độc quyền, của bất kỳ thông tin nào được công bố trên trang mạng này, hoặc bất kỳ kiểu sáng, văn bản, hình ảnh, đồ hoạ, trang, giao diện, đường dẫn, phần mềm, hoặc tài liệu, hồ sơ khác và các mục có trong hoặc được hiển thị hoặc được công bố trên trang này. Tất cả những mục và tài liệu đó được cung cấp trên cơ sở 'nguyên trạng', và quý vị hoàn toàn chịu trách nhiệm một mình về việc sử dụng chúng và về bất kỳ kết quả hoặc hậu quả nào từ việc sử dụng của quý vị. Trong nhiều trường hợp, những thông tin này được biên soạn từ nhiều nguồn khác nhau, bao gồm những nguồn vượt quá khả năng kiểm soát của Thành phố Philadelphia, và có thể thay đổi mà không cần phải thông báo trước từ Thành phố. Trừ những điều được nêu dưới đây, nghiêm cấm sử dụng thương mại (bao gồm nhưng không giới hạn bán cho người khác) mà không có văn bản đồng ý trước của Thành phố. Trong phạm vi quý vị sử dụng, áp dụng, hoặc thực hiện thông tin này trong hệ thống thông tin riêng của quý vị hoặc trong môi trường khác, hoặc nhằm mục đích riêng của quý vị, quý vị tự chịu mọi rủi ro. Trong mọi trường hợp, Thành phố, OPA, các cơ quan khác của Thành phố, hoặc các viên chức, nhân viên, đại lý, hoặc đại diện của bất kỳ cơ quan nào nói trên sẽ không chịu trách nhiệm về bất kỳ hư hỏng trực tiếp, gián tiếp, đặc biệt, nhằm trừng phạt, ngẫu nhiên, cảnh cáo hoặc do hậu quả gây ra phát sinh từ việc quý vị truy cập hoặc sử dụng trang mạng này hoặc bất kỳ thông tin nào được hiển thị trên trang mạng này, hoặc phát sinh từ trang mạng này hoặc ưừ bất kỳ điều nào có trong hoặc được hiển thị trên trang mạng này. Không thông tin nào có trong hoặc được hiển thị trên trang mạng này cấu thành hoặc nhằm mục đích cấu thành ý kiến tư vấn pháp lý của Thành phố hoặc bất kỳ cơ quan, viên chức, nhân viên, đại lý, luật sư, hoặc đại diện nào của Thành phố.",
	"external-sites-title": "Các trang bên ngoài",
	"external-sites": "Trang mạng này có thể có các đường dẫn đến những trang khác trên Internet do các bên khác không phải Thành phố vận hành và có thông tin có thể làm người sử dụng quan tâm. Thành phố không kiểm soát những trang này và không chịu trách nhiệm về nội dung hoặc tính hữu dụng của những trang này hoặc nội dung trong đó. Những đường dẫn đến các trang này không phải là sự chứng thực hay đề nghị củ acác trang này hoặc của bất kỳ sản phẩm hay dịch vụ thương mại hoặc khác mà có thể được quảng cáo hoặc có trên đó; và Thành phố cũng không ủng hộ quan điểm hay sự kiện trình bày trên đó. Những câu hỏi và mối quan ngại về nội dung của bất kỳ trang bên ngoài nào được liên kết có thể được chuyển trực tiếp đến quản trị viên của trang bên ngoài này.",
	"copyright-title": "Bản quyền, tên thương mại và thương hiệu dịch vụ",
	"copyright": "Thương hiệu dịch vụ và tên thương mại có trong hoặc được hiển thị trên trang này, và nội dung của những trang được liên kết do các bên thứ ba vận hành là tài sản của chủ sở hữu tương ứng của chúng. Tất cả những thiết kế, thông tin, nội dung, hình ảnh, đồ hoạ, trang, giao diện, đường dẫn, phần mềm, và các mục cũng như tài liệu khác có trong hoặc được hiển thị trên trang này và sự lựa chọn cũng như thu xếp từ đó, là tài sản của Thành phố Philadelphia. Giữ toàn quyền. Được phép sao chụp điện tử và in thông tin từ trang này chỉ nhằm mục đích cá nhân, hoặc chia sẻ với người khác với điều kiện là tất cả những thông tin được sao chụp, in ra, và/hoặc chia sẻ không tính phí đối với người nhận và chính xác như được in trên trang mạng này, mà không có bất kỳ chỉnh sửa hay bổ sung nào.",
	"communications-title": "Giao tiếp qua trang mạng",
	"communications": "Trong mọi trường hợp, bất kỳ giao tiếp nào được thực hiện qua e-mail, thông điệp hoặc các chức năng giao tiếp khác của bất kỳ trang web nào của Thành phố đều thiết lập thông báo pháp lý hoặc thông báo khác đến Thành phố, OPA, bất kỳ cơ quan nào khác của Thành phố, hoặc bất kỳ viên chức, nhân viên, đại lý, hoặc đại diện của OPA hoặc Thành phố, bao gồm nhưng không giới hạn (i) thông báo pháp lý theo yêu cầu của luật pháp, quy tắc hoặc quy định của liên bang, tiểu bang, hoặc địa phương về bất kỳ yêu cầu hiện tại hoặc có khả năng hoặc nguyên nhân hành động đối với Thành phố hoặc bất kỳ cơ quan, viên chức, nhân viên, đại lý, hoặc đại diện nào; (ii) bất kỳ hình thức thông báo nào yêu cầu theo quy định hoặc chính sách của OPA hoặc bất kỳ pháp luật liên bang, tiểu bang, hoặc địa phương áp dụng đối với OPA; hoặc (iii) bất kỳ hình thức thông báo nào yêu cầu theo bất kỳ công văn nào do OPA ban hành.",
	"misc-disc-title": "Khác",
	"misc-disc": "Các điều khoản và điều kiện nói trên cũng như mọi tranh chấp phát sinh từ đó sẽ được chi phối, giải thích và quyết định theo pháp luật của Khối Thịnh Vượng Pennsylvania. Thành pôố có quyền chỉnh sửa và thay đổi các điều khoản và điều kiện nói trên vào bất kỳ lúc nào và không cần thông báo trước. Các tiêu đề chỉ nhằm mục đích thuận tiện và không xác định, giới hạn, mở rộng hay miêu tả mục đích của bất kỳ quy định nào trong Điều Khoản Sử Dụng và Khước Từ này.",
	"disc-revenue-taxes": "Lưu ý: Sở Thuế Vụ có trách nhiệm thu thuế bất động sản.  Vui lòng truy cập {0}Trang Web của Sở Thuế Vụ{1} để biết thông tin về việc xuất hoá đơn, thu tiền và hạch toán thuế bất động sản hoặc gọi đến số 215-686-6442.",
	"disc-homestead": "Nếu được chấp thuận cho Exemption Homestead , số tiền có thể được tìm thấy trong các cột được miễn thuế . Bạn không đủ điều kiện cho Exemption Homestead nếu bạn đã có một giảm hoặc đang theo học trong Chương trình Người cư ngụ lâu năm chủ (LOOP).",
	"no-matches": "Không tìm thấy kết quả cho {0}.",
	"for-best-results": "Để có kết quả tốt nhất, hãy thử nhập số tài khoản của tài sản quý vị.",
	"click-submit-inquiry": "Nhấp vào đây để gửi yêu cầu",
	"error-account-fail": "Xảy ra lỗi khi tìm kiếm tài sản trong cơ sở dữ liệu. Vui lòng thử lại.",
	"error-loop-fail": "Xảy ra lỗi khi tìm kiếm tài sản trong cơ sở dữ liệu. Vui lòng thử lại.",
	"error-address-fail": "Xảy ra lỗi khi xác minh địa chỉ. Vui lòng thử lại.",
	"error-default": "Đã xảy ra lỗi. Vui lòng thử lại.",
	"field-required": "Trường này là bắt buộc."
});